const actionTypes = {
  // all books by category
  FETCH_BOOKS_FROM_CATEGORY: 'FETCH_BOOKS_FROM_CATEGORY',
  FETCH_BOOKS_FROM_CATEGORY_REQUEST: 'FETCH_BOOKS_FROM_CATEGORY_REQUEST',
  FETCH_BOOKS_FROM_CATEGORY_SUCCESS: 'FETCH_BOOKS_FROM_CATEGORY_SUCCESS',
  FETCH_BOOKS_FROM_CATEGORY_ERROR: 'FETCH_BOOKS_FROM_CATEGORY_ERROR'
};

export default actionTypes;
